version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs"]

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/AbhayFernandes/review_tool"

[[analyzers]]
name = "docker"

[[transformers]]
name = "gofmt"

[[transformers]]
name = "prettier"