version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs"]

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/AbhayFernandes/review_tool"
  import_paths = ["github.com/AbhayFernandes/review_tool/cmd/api", "github.com/AbhayFernandes/review_tool/cmd/crev", "github.com/AbhayFernandes/review_tool/cmd/job-processor", "github.com/AbhayFernandes/review_tool/pkg/proto", "github.com/AbhayFernandes/review_tool/pkg/ssh"]

[[analyzers]]
name = "docker"

[[transformers]]
name = "gofmt"

[[transformers]]
name = "prettier"
