version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - STAGE=devo
    depends_on:
      - db
    volumes:
      - ./data/diffs:/diffs

  job-processor:
    build:
      context: .
      dockerfile: cmd/job-processor/Dockerfile
    environment:
      - STAGE=devo
    depends_on:
      - db

  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "80:80"

  db:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb 
    attach: false
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/var/lib/mongo
