version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - STAGE=devo
    depends_on:
      - scylla

  job-processor:
    build:
      context: .
      dockerfile: cmd/job-processor/Dockerfile
    environment:
      - STAGE=devo
    depends_on:
      - scylla

  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "80:80"

  scylla:
    image: scylladb/scylla
    container_name: scylla
    attach: false
    expose:
      - "9042"
    volumes:
      - ./data/scylla:/var/lib/scylla
