services:
  api:
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - STAGE=devo
    depends_on:
      - db
    volumes:
      - ./data/diffs:/diffs

  job-processor:
    build:
      context: .
      dockerfile: cmd/job-processor/Dockerfile
    environment:
      - STAGE=devo
    depends_on:
      - db

  web:
    build:
      context: . 
      dockerfile: web/Dockerfile
    ports:
      - "3000:3000"

  db:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb 
    attach: false
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
