version: "3.9"
# TODO: Add monitoring for this stuff

services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.apisecure.address=:8080"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=superman@abhayf.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    image: ghcr.io/abhayfernandes/api:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`crev.abhayf.com`)"
      - "traefik.http.routers.api.entrypoints=apisecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.services.api.loadbalancer.server.scheme=h2c"
      - "traefik.http.middlewares.api-grpc.grpcWeb.allowOrigins=*"
      - "traefik.http.routers.api.middlewares=api-grpc"
    environment:
      - STAGE=devo
    depends_on:
      - db
    volumes:
      - diffs:/diffs
    deploy:
      mode: replicated
      replicas: 3

  job-processor:
    image: ghcr.io/abhayfernandes/job-processor:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - STAGE=devo
    depends_on:
      - db
    expose:
      - "69420"

  web:
    image: ghcr.io/abhayfernandes/web:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`crev.abhayf.com`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      mode: replicated
    expose:
      - "3000"

  db:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb 
    attach: false
    expose:
      - "27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  letsencrypt:
  mongodb_data:
  diffs:
