name: Sync Branches

on:
  push:
    branches:
      - main

jobs:
  sync-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch All Branches
        run: git fetch --all

      - name: Merge Main into Dev
        run: |
          git checkout dev
          git rebase main

      - name: Push Changes to Dev
        run: git push origin dev --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

